version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always

